name: safe-parking

services:
    postgres:
        image: postgres:18.4-alpine3.24
        restart: unless-stopped
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
        ports:
            - "5439:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "app", "-d", "app"]
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    postgres-data:
